# Generated by Django 5.0.6 on 2024-06-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0003_test_mode_remove_user_password1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_mode',
        ),
    ]
