# Generated by Django 5.0.6 on 2024-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0004_delete_test_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted',
            field=models.CharField(choices=[('request', 'request'), ('pending', 'pending'), ('accept', 'accept')], default='request', max_length=20),
        ),
    ]
