# Generated by Django 5.0.6 on 2024-06-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0005_alter_friendrequest_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='accepted',
            new_name='request_staus',
        ),
    ]
