# Generated by Django 5.0.6 on 2024-06-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0006_rename_accepted_friendrequest_request_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='request_staus',
            new_name='request_status',
        ),
    ]
